### ISSUE TITLE
PMD errors with non-default mbuf size

### ISSUE THREAD

**Issue by mafrankSWXTCH** [google/compute-virtual-ethernet-dpdk#3]
Greetings,

I'm working with the GVE PMD for DPDK 23.07 and I've encountered strange behavior. From what I've observed, if the mbuf size is greater than `DEFAULT_MBUF_DATA_SIZE` (2048 + 128) then the PMD 
1.) _Eventually_ becomes unable to send packets. The number of packets that are sent varies before the driver enters a bad state; `test-pmd` stops exactly at 178, but my app stops at 1023.
2.) Fails to destroy the tx and rx queues. The exact error messages reported are
```
gve_adminq_parse_err(): AQ command failed with status -11
gve_stop_tx_queues(): failed to destroy txqs
gve_adminq_parse_err(): AQ command failed with status -11
gve_stop_rx_queues(): failed to destroy rxqs
```

I'm able to invariably reproduce both errors by modifying `test-pmd` with the following patch (which simply changes the mbuf size to 4096). 
```
diff --git a/app/test-pmd/testpmd.c b/app/test-pmd/testpmd.c
index 938ca035d..ff0c9ab01 100644
--- a/app/test-pmd/testpmd.c
+++ b/app/test-pmd/testpmd.c
@@ -217,7 +217,7 @@ uint32_t burst_tx_retry_num = BURST_TX_RETRIES;

 uint32_t mbuf_data_size_n = 1; /* Number of specified mbuf sizes. */
 uint16_t mbuf_data_size[MAX_SEGS_BUFFER_SPLIT] = {
-       DEFAULT_MBUF_DATA_SIZE
+       4096
 }; /**< Mbuf data space size. */
 uint32_t param_total_num_mbufs = 0;  /**< number of mbufs in all pools - if
                                       * specified on command-line. */
```

Also, in case it matters, I was testing with the `n2-custom-8-16384` machine type, and the full `test-pmd` command is
`sudo <path_to_testpmd>/dpdk-testpmd -n 1 -a 0:00:05.0 -- --port-topology=chained --nb-cores 1 --txq 1 --rxq 1 --mbcache=512 --txd=1024 --forward-mode=txonly --stats-period 1  --txpkts=1460 --tx-ip=10.1.216.39,10.1.216.40 --eth-peer=0,00:0d:3a:1a:5d:b3`

I have not seen anything in the DPDK docs related to the PMD being affected by the mbuf size; plus this patch works with other PMDs (Mlx5, ENA, Virt-IO), so I don't believe I'm doing something wrong.

Please let me know if you need more information. Or if I am posting to the wrong channel, please redirect me to the correct one.

Thanks!

**Comment by josh8551021** [comment]
Good catch. The packet buffer size for RX is dictated by the data room of the mbuf. Unfortunately, the driver does not curently enusre that that value is correct (the GQ driver only supports 2K and 4K packet buffer sizes). The behavior you are seeing is actually just the driver sending attempting to send initial packets and failing.

A patch should be coming soon to remedy this, but in the mean time, if you wish to use 4K buffers, make sure that the data room is equal to 4K instead of the entire mbuf size by setting the mbuf-size to 4096+128 = 4224B.

**Comment by mafrankSWXTCH** [comment]
I can confirm that changing the mbuf size fixed my problem. Thank you 👍

**Comment by josh8551021** [comment]
Progress for patch upstreaming can be tracked at: https://patchwork.dpdk.org/project/dpdk/patch/20231111003410.2950594-1-joshwash@google.com/

Once upstreamed, this repository will be updated with the patch.
